// 外部通信を遮断したローカル画面で操作・計算一致・狭い画面を確認する。
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const {chromium}=require('playwright');
const ROOT=path.resolve(__dirname,'..'),OUT=path.join(ROOT,'work/lab-review');
const server=http.createServer((req,res)=>{const p=path.resolve(ROOT,'.'+(req.url==='/'?'/index.html':req.url.split('?')[0]));
  if(path.relative(ROOT,p).startsWith('..')||!fs.existsSync(p)){res.writeHead(404);res.end();return;}
  res.setHeader('Content-Type',({'.js':'application/javascript','.html':'text/html','.css':'text/css','.png':'image/png'})[path.extname(p)]||'application/octet-stream');fs.createReadStream(p).pipe(res);});
let browser,checks=0;const eq=(a,b,msg)=>{assert.deepEqual(a,b,msg);checks++;};
(async()=>{try{
  fs.mkdirSync(OUT,{recursive:true});await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+server.address().port;
  browser=await chromium.launch({channel:'msedge',headless:true});const context=await browser.newContext({viewport:{width:1100,height:900},serviceWorkers:'block'});
  await context.route('**/*',r=>r.request().url().startsWith(origin)?r.continue():r.fulfill({status:200,body:'',contentType:'application/javascript'}));
  await context.addInitScript(()=>{localStorage.setItem('guestMode','1');localStorage.setItem('guestHideRegPrompt','1');localStorage.setItem('guest_series',JSON.stringify([{id:'lab-fixture',name:'ラボ検証',created_at:'2026-10-09T00:00:00Z'}]));});
  const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(origin);
  await page.evaluate(()=>{showPage('lab');switchLab('calc');});
  await page.selectOption('#labPokeSelect','カメックス');await page.selectOption('#labItem1','ふんばりベルト');
  const base=await page.evaluate(()=>labCalcResult.防御);
  const belt=()=>page.locator('#labEffects input[value="ふんばりベルト"]');
  eq(await belt().isChecked(),false,'default OFF');await belt().check();
  eq(await page.evaluate(()=>labCalcResult.防御),Math.round(base*1.28*1e8)/1e8,'ON increases defense');
  await belt().uncheck();eq(await page.evaluate(()=>labCalcResult.防御),base,'OFF restores defense');
  await belt().check();await page.selectOption('#labItem1','');await page.selectOption('#labItem1','ふんばりベルト');
  eq(await belt().isChecked(),false,'re-equip resets effect');await belt().check();
  const stat=await page.evaluate(()=>({...labCalcResult}));
  await page.evaluate(()=>switchLab('dmg'));await page.selectOption('#dcAtkPoke','ピカチュウ');await page.selectOption('#dcDefPoke','カメックス');
  await page.selectOption('#dcDefItem1','ふんばりベルト');await page.locator('#labDmgCalcPanel button',{hasText:'計算する'}).click();
  const before=await page.locator('#dcDmgOutNormal').innerText();
  await page.locator('#dcDefEffects input[value="ふんばりベルト"]').check();
  eq(await page.evaluate(()=>dcDefStats.防御),stat.防御,'stats and DC use identical defense');
  eq(await page.locator('#dcDmgOutNormal').innerText()!==before,true,'defender effect changes damage');
  await page.selectOption('#dcAtkItem1','エナジーアンプ');const off=await page.locator('#dcDmgOutNormal').innerText();
  await page.locator('#dcAtkEffects input[value="エナジーアンプ"]').check();
  eq(await page.locator('#dcDmgOutNormal').innerText()!==off,true,'amp changes damage');
  eq(await page.locator('#dcDefEffects input[value="ふんばりベルト"]').isChecked(),true,'attacker and defender independent');
  await page.selectOption('#dcAtkPoke','モルペコ');const heal=await page.locator('#dcDmgOutPassive').innerText();
  await page.locator('#dcAtkEffects input[value="エナジーアンプ"]').uncheck();
  eq(await page.locator('#dcDmgOutPassive').innerText(),heal,'amp does not increase healing');
  await page.selectOption('#dcAtkItem1','レスキューフード');const self=await page.locator('#dcDmgOutPassive').innerText();
  await page.selectOption('#dcAtkHealTarget','ally');
  eq(await page.locator('#dcDmgOutPassive').innerText()!==self,true,'ally target applies hood');
  await page.selectOption('#dcAtkHealTarget','self');eq(await page.locator('#dcDmgOutPassive').innerText(),self,'self target excludes hood');
  await page.selectOption('#dcAtkItem1','エナジーアンプ');await page.locator('#dcAtkEffects input[value="エナジーアンプ"]').check();
  await page.locator('#labDmgCalcPanel').screenshot({path:path.join(OUT,'effects-desktop.png')});
  await page.setViewportSize({width:390,height:844});
  await page.locator('#labDmgCalcPanel').screenshot({path:path.join(OUT,'effects-mobile.png')});
  eq(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'no mobile overflow');
  eq(errors,[],'no page errors');
  console.log('ALL PASS — '+checks+' effects browser checks; real DB writes: 0');
}catch(e){console.error(e);process.exitCode=1;}finally{if(browser)await browser.close();await new Promise(r=>server.close(r));}})();
